### ISSUE TITLE
Get prefab merging running again

### ISSUE THREAD

**Issue by FlaShG** [FlaShG/GitMerge-for-Unity#54]
Prefab merging isn't working at all at this time.

* A prefab file (serialized as text) with a merge conflict is not recognized as a prefab asset in Unity, so it can't be dragged into the field. In fact, it cannot be used in any way in the editor.
* When the file is manually checked out to a conflict-less version, GMfU doesn't find any property changes.

**Comment by dziemich** [comment]
Does this mean, the tool is only suitable for resolving scene conflicts at this point?

**Comment by FlaShG** [comment]
In my most recent tests, yes.

**Comment by EthanGrahn** [comment]
I'm just starting to take a look at this and have some potential workarounds to begin fixing the prefab merge. These are only starting points though. First would be to have the prefab tab of the editor use UnityEngine.Object to be able to drop in the prefab with conflicts. That will require additional processing after the fact since it still cannot be treated as a GameObject. Second would be to comment out the merge conflict indicators in the yaml code of the prefab. This allows it to load as a GameObject again, but additional parsing will be needed since that will not mesh with your current system.

**Comment by FlaShG** [comment]
@EthanGrahn when having GMfU in a project, it's a good idea to either serialize files into binary or tell the VCS to skip automatic merging for scene and prefab files. The primary issue with prefab merging at this time is the complexity that the nested prefabs update introduced to how prefabs work. Properties are not longer just things with values in them, but can have overrides and references to other prefabs, which would need to be supported by the prefab merge process.

**Comment by FlaShG** [comment]
Prefabs are now working on again on a base level. I have not gotten into nested prefabs or prefab variants yet, so those will likely not work yet.
